/component/title:
  title: Open Door Go North

/component/uuid:
  uuid: ED07584D-7070-4C04-A90B-1F79AAFBC26F

/component/src:
  url: file:///site/

/component/dst:
  url: file:///dist/

/component/meta:
  meta:
    es:
      url: es://sqlite/odgn.sqlite

/component/patterns:
  include: 
    - '**/*'
  exclude:
    - .DS_Store
